name: Chaining Jobs

on:
  workflow_dispatch:
    inputs:
      run-job-3:
        description: "Run Job 3"
        required: true
        type: boolean

concurrency:
  group: my-test-${{github.ref}}
  cancel-in-progress: true

jobs:
  job1:
    name: "Job 1"
    runs-on: ubuntu-latest
    steps:
      - name: Output for Job 1
        run: echo "Hello from Job 1. Run Job 3 equals ${{github.event.inputs.run-job-3}}"

  job2:
    name: "Job 2"
    runs-on: ubuntu-latest
    needs:
      - job1
    steps:
      - name: Output for Job 2
        run: echo "Hello from Job 2"

  job3:
    name: Job 3
    if: github.event.inputs.run-job-3 =='true'
    runs-on: ubuntu-latest
    needs:
      - job1
    steps:
      - name: Outpur for Job 3
        run: echo "Hello from Job 3"

  job4:
    name: Job 4
    runs-on: ubuntu-latest
    # if: always()
    needs:
      - job2
      - job3
    steps:
      - name: Output for Job 4
        run: echo "Hello from Job 4"
