name: Variables and Context

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Person to Greet"
        default: "World"
        required: true

jobs:
  job1:
    runs-on: ubutu-latest
    steps:
      - name: Dump Github Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
