name: Variables and Context

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Person to greet"
        default: "La La Land"
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

  job2:
    runs-on: ubuntu-latest
    output1: ${{steps.step1.outputs.step1value}}
    output2: ${{steps.step1.outputs.step2value}}
    steps:
      - name: Step 1
        id: step1
        run: echo "step1value=hello" >> $GITHUB_OUTPUT
      - name: Step 2
        id: step2
        run: echo "step2value=world1 1" >> $GITHUB_OUTPUT

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Output
        run: echo ${{needs.job2.outputs.output1}} || ${{needs.job2.outputs.output2}}
