name: Variables and Context

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Person to greet"
        default: "La La Land"
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
